version: '3'

services:
  # collector:
  #   container_name: collector
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/home/node/collector
  #     - ./node_modules:/home/node/collector/node_modules
  #   networks:
  #     - tm-collector-network
  #   depends_on:
  #     - db
  db:
    container_name: tm-database
    image: postgres
    volumes:
      - tm-data:/data
    ports:
      - '${TM_DB_PORT}:${TM_DB_PORT}'
    networks:
      - tm-network
    environment:
      - POSTGRES_DB=${TM_DB_DATABASE}
      - POSTGRES_USER=${TM_DB_USERNAME}
      - POSTGRES_PASSWORD=${TM_DB_PASSWORD}
  db_mongo:
    container_name: tm-database-mongo
    image: mongo
    volumes:
      - tm-data:/data
    ports:
      - '${TM_MONGO_DB_PORT}:${TM_MONGO_DB_PORT}'
    networks:
      - tm-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME: ${TM_MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD: ${TM_MONGO_DB_PASSWORD}
  db_redis:
    container_name: redis
    image: redis:alpine
    volumes:
      - tm-data:/data
    ports:
      - '${REDIS_DB_PORT}:${REDIS_DB_PORT}'
    networks:
      - tm-network
  # migrations:
  #   container_name: migrations
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   command: ['yarn', 'typeorm', 'migration:run', '-c', 'tm']
  #   networks:
  #     - tm-collector-network
  #   depends_on:
  #     - db
volumes:
  tm-data:

networks:
  tm-network:
    driver: bridge
