version: '3'

services:
  # collector:
  #   container_name: collector
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./:/home/node/collector
  #     - ./node_modules:/home/node/collector/node_modules
  #   networks:
  #     - tm-collector-network
  #   depends_on:
  #     - db
  db:
    container_name: tm-collector-database
    image: postgres
    volumes:
      - tm-collector-data:/data
    ports:
      - '${TM_DB_PORT}:${TM_DB_PORT}'
    networks:
      - tm-collector-network
    environment:
      - POSTGRES_DB=${TM_DB_DATABASE}
      - POSTGRES_USER=${TM_DB_USERNAME}
      - POSTGRES_PASSWORD=${TM_DB_PASSWORD}
  # migrations:
  #   container_name: migrations
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #   command: ['yarn', 'typeorm', 'migration:run', '-c', 'tm']
  #   networks:
  #     - tm-collector-network
  #   depends_on:
  #     - db
volumes:
  tm-collector-data:

networks:
  tm-collector-network:
    driver: bridge
